Repository AY2122S1-CS2113T-W11-4/tp, pull requests merged in 2021-10, with the labels that each got.

#32 Add assertion and logging for Ui class and AddDishIngrCommand class
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddDishIngrCommand.java
Labels: type.Task, priority.Medium

#51 Added Logging and Assertions for ClearListCommands
  log/programLog.log
  src/main/java/seedu/duke/DishList.java
  src/main/java/seedu/duke/IngredientList.java
  src/main/java/seedu/duke/command/ClearAllCommand.java
  src/main/java/seedu/duke/command/ClearDishCommand.java
  src/main/java/seedu/duke/command/ClearIngrCommand.java
Labels: priority.Medium

#122 Add ability to set expiry date of ingredients
  src/main/java/seedu/foodorama/Ingredient.java
  src/main/java/seedu/foodorama/IngredientList.java
  src/main/java/seedu/foodorama/InputParser.java
  src/main/java/seedu/foodorama/Ui.java
  src/main/java/seedu/foodorama/command/CommandNames.java
  src/main/java/seedu/foodorama/command/SetIngrExpiryCommand.java
  src/main/java/seedu/foodorama/storage/Storage.java
Labels: type.Enhancement, priority.Medium

#147 Update AboutUs.md with team photos
  docs/AboutUs.md
  docs/images/aboutus/arvind.png
  docs/images/aboutus/jianhui.png
  docs/images/aboutus/rakesh.png
  docs/images/aboutus/renzo.png
Labels: priority.Low

#148 Fix AboutUs.md bug that causes the images to not appear correctly
  docs/AboutUs.md
Labels: priority.Low

#151 Fix Renzo code review bugs
  src/main/java/seedu/foodorama/Dish.java
  src/main/java/seedu/foodorama/Ingredient.java
  src/main/java/seedu/foodorama/Ui.java
  src/main/java/seedu/foodorama/command/AddDishCommand.java
  src/main/java/seedu/foodorama/command/AddDishWasteCommand.java
  src/main/java/seedu/foodorama/command/AddIngrCommand.java
  src/main/java/seedu/foodorama/command/AddIngrStoredCommand.java
  src/main/java/seedu/foodorama/command/ClearAllCommand.java
  src/main/java/seedu/foodorama/command/EditDishCommand.java
  src/main/java/seedu/foodorama/command/EditIngrCommand.java
  src/main/java/seedu/foodorama/command/FindCommand.java
  src/main/java/seedu/foodorama/command/GraphCommand.java
  src/main/java/seedu/foodorama/command/HelpCommand.java
  src/main/java/seedu/foodorama/command/LinkCommand.java
  src/main/java/seedu/foodorama/command/ListCommand.java
  src/main/java/seedu/foodorama/command/SetDishLimitCommand.java
  src/main/java/seedu/foodorama/command/SetIngrLimitCommand.java
  src/main/java/seedu/foodorama/command/SortDishCommand.java
  src/main/java/seedu/foodorama/command/SortIngrCommand.java
Labels: priority.High
